/**
 * Enumeration of action types that can be dispatched in MDXContentReducer.
 */
export enum MDXContentActionEnum {
  SET_STATE,
  SET_API_BASE_INDEX,
  SET_IS_API,
  SET_API_PLAYGROUND_INPUTS,
  SET_OPEN_API_PLAYGROUND_PROPS,
  SET_SELECTED_BODY_CONTENT_TYPE,
  SET_SELECTED_RESPONSE_CONTENT_TYPE,
  SET_USER_DEFINED_EXAMPLES,
  SET_CURRENT_TABLE_OF_CONTENTS_SECTION,
  SET_CONTENT_WIDTH,
  SET_PARAM_GROUPS,
  SET_API_PLAYGROUND,
  REGISTER_HEADING,
  UNREGISTER_HEADING,
}
